---
- name: Test play
  hosts: all

  tasks:
    - name: Hello world
      debug:
        msg: "Hello, world!"

    - name: Uninstall Apache
      sudo: true
      apt:
        name: apache2
        state: absent

    - name: Install Vim
      become: yes
      apt:
        name: vim
        state: present
        update_cache: true

    - name: Install mc
      become: yes
      apt:
        name: mc
        state: present
        update_cache: true

    - name: Print Linux version
      shell: echo $(cat /etc/os-release) >testfile
      args:
        chdir: /home/vagrant
        creates: testfile