# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
  
    config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
  
    config.vm.define "slave" do |slave|
      slave.vm.network "private_network", ip: "192.168.56.5"
  
      slave.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "slave.yaml"
        ansible.become = true
      end
    end
  
    config.vm.define "master", primary: true do |master|
      master.vm.network "private_network", ip: "192.168.56.4"
  
      master.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "master.yaml"
      end
    end
  end